### ISSUE TITLE
don’t autocomplete emails in the invite (privacy issue)

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#10]

**Comment by jamesnvc** [comment]
Currently, the only emails you can see are users that are already in your group(s)

**Comment by pkobrien** [comment]
Privacy is going to be a top-level priority for me. The environment created by Braid must be safe and secure. We *must* respect and protect the identity and privacy of each and every user of the system.

**Comment by jamesnvc** [comment]
Agreed, we can change this.  Just saying that it isn't as horrible as it could be right now :p

**Comment by rafd** [comment]
(ex. you can see everyone’s email on Slack)

**Comment by jamesnvc** [comment]
closed by https://github.com/braidchat/braid/commit/8e8624ca5e751aea3428106a9091c411bd984716.

User emails are still sent to the user, to be displayed instead of nicknames if unset, but we could also get rid of that if we required users to set nicknames when signing up

**Comment by pkobrien** [comment]
do not expose email address without consent period - user provides a nickname or the system assigns some random one that the user can easily change.

**Comment by pkobrien** [comment]
do not expose a single piece of personal information about a user without their EXPLICIT CONSENT.
