### ISSUE TITLE
search ends up moving things off-screen and becoming unscrollable

### ISSUE THREAD

**Issue by jamesnvc** [braidchat/meta#102]
Via @pkobrien

**Comment by pkobrien** [comment]
not quite
did a search and one convo came back
went back to my prev convo, still on-screen
type a response - scrollbar no longer there
maybe a focus issue or who knows what
hope that helps

**Comment by braid-sync** [comment]
can you scroll with your touchpad (ie. sideways?)

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by jamesnvc** [comment]
Nope

**Comment by jamesnvc** [comment]
Happening to me too — related to https://github.com/braidchat/meta/issues/98 ?

**Comment by rafd** [comment]
closing b/c new search no longer combines search results with your message inbox

https://github.com/braidchat/braid/commit/8f66b4a084b2209e7649f8eccccf572cd171c95f
