### ISSUE TITLE
finish implementing sidebar

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#108]

**Comment by braid-sync** [comment]
also: https://app.asana.com/0/46955048022389/79565089686087

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by rafd** [comment]
closing this issue, splitting out into new ones:
https://github.com/braidchat/meta/issues/224
https://github.com/braidchat/meta/issues/220
https://github.com/braidchat/meta/issues/221
https://github.com/braidchat/meta/issues/219
