### ISSUE TITLE
consider changing auto-complete behaviour of # in a message

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#111]
currently, typing # will open an auto-complete, and selecting one of the options would tag the conversation (and remove the tag from the message)

suggested change:
typing # would still open the auto-complete, but when selecting a tag, the tag would be mentioned in the chat (ie. displaying inline with the rest of the words, just highlighted as a link)

instead, to add a tag while chatting:
 type \ followed by a tag-name, showing a universal auto-complete for adding tags, users, and running commands

also maybe trigger the autocomplete with a keyboard shortcut, ex TAB - T

would work similarly with mentioning/adding users (@ would just mention, TAB - U would show ui for adding)

should also allow adding tags via UI

\ autocomplete would only be triggered if \ is the first character in a message

**Comment by rafd** [comment]
@jamesnvc would love to hear your thoughts

**Comment by pkobrien** [comment]
awesome - let's try it

**Comment by jamesnvc** [comment]
I like it, seems useful; having a  way of telling people about tags seems like a good idea.

**Comment by pkobrien** [comment]
why did I struggle so much - just because I'm tired or what was I missing

**Comment by jamesnvc** [comment]
@pkobrien not working yet, still just thinking about how to do it

**Comment by pkobrien** [comment]
ok, good to know

**Comment by jamesnvc** [comment]
Reason for backslash instead of forward-slash? Might be more familiar, IRC-style

**Comment by rafd** [comment]
no reason. forward slash it is.

**Comment by pkobrien** [comment]
+1 on maintaining IRC conventions as much as possible
/shrugs

**Comment by rafd** [comment]
done https://github.com/braidchat/braid/commit/26fddb57236b88141aa3d60c643c6e6b8f57e388

user mentions still TODO
