### ISSUE TITLE
image and video embeds

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#112]
show small version inline, on-click or on-hover make it larger

maybe also for code-snippet embeds

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/79565089686046/f
---[aa]

**Comment by rafd** [comment]
image uploads work, but how they are displayed needs to be changed

want similar display for links to media content (ex. youtube links, imgur links)
for now let's just use http://embed.ly/

**Comment by braid-sync** [comment]
addressed by: https://github.com/braidchat/braid/commit/ceed2248bc3bd79ca1733df2be0b4955918a9ff4

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
