### ISSUE TITLE
if you click on a channel that you’re not subscribed to show channel name and subscribe button

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#115]
clicking on channel is a search initiated by the sidebar (not yet implemented)

heading would look like:

#foobar [subscribe]
(conversations below)

**Comment by braid-sync** [comment]
related to https://app.asana.com/0/46955048022389/79565089686062

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by rafd** [comment]
done https://github.com/braidchat/braid/commit/64838d85320a70f9fa596878e25372b62637d408
