### ISSUE TITLE
show keyboard shortcuts / instructions in UI

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#117]

**Comment by rafd** [comment]
https://github.com/braidchat/braid/commit/fbaa955961de75f53f3ce0d44a3d7e07365fa826 done

**Comment by pkobrien** [comment]
also need transient lists of similar info

**Comment by rafd** [comment]
@pkobrien please clarify

**Comment by pkobrien** [comment]
if we end up with a lot of keyboard shortcuts there should be a way to pop up a list of those for reference until I get used to them
