### ISSUE TITLE
tag tasks that are recommended for community to tackle

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#124]
+ mention it on https://github.com/braidchat/meta/wiki/Contributing

**Comment by rafd** [comment]
what tag name to use? 

#easy-pickings
#community
#do-me
#fix-me

other?

**Comment by rafd** [comment]
https://github.com/braidchat/meta/issues?q=is%3Aopen+is%3Aissue+label%3Ahelp-wanted
