### ISSUE TITLE
remove need for AWS keys, mailgun password, user passwords

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#13]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/78693400450373/f
---[aa]

**Comment by pkobrien** [comment]
Have no idea what this means. Can anyone explain it besides rafd (I don't want to waste his valuable time)?

**Comment by jamesnvc** [comment]
Currently the webapp needs AWS keys for uploading avatars, mailgun credentials to send invitation emails, and user passwords for seeding the initial users.  I guess we want a way for people to get up & running without requiring these.

**Comment by rafd** [comment]
done https://github.com/braidchat/braid/commit/bba74f14fb2a28df0e11c680362988a56ec0cfe9
