### ISSUE TITLE
dont send emails to client

### ISSUE THREAD

**Issue by jamesnvc** [braidchat/meta#138]
Now that it's require everyone have a nickname, we can avoid sending emails to the client alltogether.  Just need to verify that all existing users have nicknames.

**Comment by braid-sync** [comment]
may want to still ask for email for password recovery purposes?

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
…can avoid email if auth via external service

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
perhaps change the email content (to a verification)

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
if register via an invite email, shouldn’t need to verify

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
(also shouldn’t have to ask them for the email on sign-up if they came from an invite email)

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
Sure, we can store the email, just not let  other users see it.

[--- Commented from Asana.com
#commenter James Cash
---[aa]

**Comment by braid-sync** [comment]
To clarify: by this I mean "when sending the list of other users to a connected client, just send id, nickname, avatar, not email"

[--- Commented from Asana.com
#commenter James Cash
---[aa]

**Comment by braid-sync** [comment]
I don't think we do ask for email on register, it's included in the invitation they activate.

[--- Commented from Asana.com
#commenter James Cash
---[aa]

**Comment by jamesnvc** [comment]
closed by https://github.com/braidchat/braid/commit/1c508311833df46a0845603ec71a1edeff81699e
