### ISSUE TITLE
review how focus of compose field jumps around

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#154]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/80471815316190/f
---[aa]

**Comment by jamesnvc** [comment]
To review why it happens: The "new thread" field has a constant react-id, so when the new thread gets created, it's "add message" field has a react id based on the new thread id.  Previously, we tried having the new thread field make a new id for the prospective new thread; however, with that approach, when a new thread comes in, the threads component gets re-rendered, the "id of thread that would be created from the compose field" changes, resulting in the compose field being re-created, losing all the content that had been typed thus far.
