### ISSUE TITLE
indicate difference between tag mention vs. tag apply in autocomplete window

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#164]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/80944178922410/f
---[aa]

**Comment by pkobrien** [comment]
cuz I f*ck this up on a daily

**Comment by braid-sync** [comment]
no longer any difference since: https://github.com/braidchat/braid/commit/bdd3d63da5d12bc4683eba547bfeee92a9c14236

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
