### ISSUE TITLE
order of messages is jumping around

### ISSUE THREAD

**Issue by jamesnvc** [braidchat/meta#165]
Seeing mesasges in a thread out of order :S

**Comment by jamesnvc** [comment]
Happening because we let the client send message created time

**Comment by braid-sync** [comment]
likely due to trusting user’s created-at

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by jamesnvc** [comment]
Should be fixed by https://github.com/braidchat/braid/commit/dfb2bf8c574ed59e1b1dc40d2743b7e024144d1e
