### ISSUE TITLE
new video to argue for the braid concept

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#17]

**Comment by pkobrien** [comment]
I'm going to encourage the community to do this kind of advocacy.

**Comment by pkobrien** [comment]
Would be nice if I had an easy way to create videos of chat sessions for: advocacy, tech support, bug reports, feature requests, code development, ...

**Comment by pkobrien** [comment]
Would be nice to be able to see videos embedded inside chat.

**Comment by pkobrien** [comment]
Would be nice to have video chat with individuals and groups. With live coding as well.

**Comment by rafd** [comment]
Good ideas. Can you add these as separate issues?

On January 11, 2016 at 11:27:20 AM, pkobrien (notifications@github.com) wrote:

Would be nice if I had an easy way to create videos of chat sessions for: advocacy, tech support, bug reports, feature requests, code development, ...

**Comment by pkobrien** [comment]
yes, can you assign it to me
