### ISSUE TITLE
don’t allow whitespace in names

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#174]

**Comment by jamesnvc** [comment]
Nicknames or tag names? Nicknames is already done

**Comment by braid-sync** [comment]
pkobrien’s name has a strange character? try autocompleting his name

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
@	patrick.keith.obrien

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
