### ISSUE TITLE
limit length of messages

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#175]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/81245061669167/f
---[aa]

**Comment by braid-sync** [comment]
should truncate the sent message? Or just not allowing sending?

[--- Commented from Asana.com
#commenter James Cash
---[aa]

**Comment by pkobrien** [comment]
what is the proposed limit

**Comment by braid-sync** [comment]
I’m thinking something large, pretty much for DoS protection; in the range of ~1MB plain text

[--- Commented from Asana.com
#commenter James Cash
---[aa]

**Comment by braid-sync** [comment]
i think something reasonable for the sake of UX protection, not just security, like 5,000 characters? see: This is 4500 chars: http://baconipsum.com/?paras=10&type=all-meat&start-with-lorem=1

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
