### ISSUE TITLE
scroll-to-bottom seems to break when threads move around

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#182]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/81753632676016/f
---[aa]

**Comment by braid-sync** [comment]
when threads are moved (due to some other thread coming in) om does not update the threads b/c they are keyed (which is as expected)

however… webkit DOES reset the scroll position of a moved dom element

:disappointed:

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
may need to do the scroll management in a parent component… ewww

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by rafd** [comment]
fixed https://github.com/braidchat/braid/commit/4e5e43eed10b4c90f1fcb5dac749bcc042d0a996
