### ISSUE TITLE
show autocomplete immediately after @, #, and /

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#186]
ie. don’t wait for an extra character to be typed

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/81753632676025/f
---[aa]

**Comment by CommonCreative** [comment]
This may be helpful to look at. - https://github.com/arosequist/om-autocomplete

**Comment by rafd** [comment]
done https://github.com/braidchat/braid/commit/19eff63f16f136277457283e7cce1e4e686ddfe4
