### ISSUE TITLE
use mount or component to manage server app state

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#189]
mount or component can be used to help manage app-state and order-dependencies when launching certain services (ex. handler/start-server! and sync/start-router!)

https://github.com/tolitius/mount

https://github.com/stuartsierra/component
+
https://github.com/danielsz/system

any advice on which to use?

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/82620223449423/f
---[aa]

**Comment by rafd** [comment]
@v47 adds on #braid-chat:

...it would allow you to co-ordinate the different pieces in the app (datomic, redis, app-server, mailing service, etc). For example, you could have 2 mailing services defined, and swap them as needed. One for actually hitting mailgun apis, and one for testing, maybe writing to a log instead...

**Comment by v47** [comment]
Hi, I don't what I am doing here. Probably you linked wrong person.

**Comment by rafd** [comment]
sorry @v47 , didn't know github would sub you like this. there is someone else on #clojurians with alias v47. you can unsub and i will delete these messages

**Comment by v47** [comment]
Good luck and have a fun with coding your project :)
