### ISSUE TITLE
resize large avatar upload images

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#199]
currently errors out with large image

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/83095825734053/f
---[aa]

**Comment by rafd** [comment]
common_create via #braid-chat:

JPEG image 2.5mb. Dimensions 2448 × 3264.  Was the one I grabbed.. my files are a mess on computer currently.
The owl ones is JPEG image - 143 KB. Dimensions 800 × 573

**Comment by rafd** [comment]
common_create via #braid-chat:

A good idea from a UX point of view would be to resize/reduce image size on the client. Even user controlled cropping. If we know the maximum image size the application will use and the maximum resolution then we can bring it down to that.

**Comment by braid-sync** [comment]
Just doing it with resize-and-crop: I'll add another task for user-controlled cropping

[--- Commented from Asana.com
#commenter James Cash
---[aa]
