### ISSUE TITLE
use Clojure(Script) to handle CSS and all of the UI

### ISSUE THREAD

**Issue by CommonCreative** [braidchat/meta#201]
Priyatam has done amazing work in codifying the design language with his Mesh library. https://github.com/facjure/mesh

And has taken it to the next level with Mala. Creating a a template for UI integrated with Om which emphasises ClojureScript all the way down. 
https://github.com/priyatam/mala

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/83113721281413/f
---[aa]

**Comment by CommonCreative** [comment]
Further inspiration - https://github.com/gadfly361/soda-ash

**Comment by CommonCreative** [comment]
We should use Devcards - https://github.com/bhauman/devcards

**Comment by jamesnvc** [comment]
What's the rationale for doing CSS in ClojureScript?  I'm happy with LessCSS, but I'm open to being convinced otherwise.

**Comment by CommonCreative** [comment]
This is a good talk on the why of generating CSS with Clojure. https://m.youtube.com/watch?v=-jnJGNDoSXc

Typically you would use Clojure when server side creation of CSS and ClojureScript when doing dynamic stuff on the client. Will probably just become Cljc in time anyways. 

Also this allows us to use the same language and tooling throughout the whole stack. If someone is coming to this project from using Sass or Post CSS. It's less for them to learn IMO.

**Comment by rafd** [comment]
as of https://github.com/braidchat/braid/commit/da74a49a522b123befc4a4533f1f3044b7f517e6 we've migrated from lessCSS to using garden

if you'd still like to suggest using mala or mesh, please open another issue
