### ISSUE TITLE
need a way to show recently active conversations

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#21]
currently, new user sees nothing

may want to auto-subscribe them to the most recent 10 conversations

or think more about this problem

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/78968160591788/f
---[aa]

**Comment by pkobrien** [comment]
I like these ideas. Would like to be able to subscribe to topics on-the-fly as well. Would like to be able to do everything within the context of the chat that inspired me to take a certain action without having to go elsewhere.

**Comment by rafd** [comment]
Can you clarify with an example?

On January 11, 2016 at 11:25:13 AM, pkobrien (notifications@github.com) wrote:

I like these ideas. Would like to be able to subscribe to topics on-the-fly as well. Would like to be able to do everything within the context of the chat that inspired me to take a certain action without having to go elsewhere.

**Comment by pkobrien** [comment]
I think I was thinking more along the line of *creating* new topics inline, which is what you are going to do with the new version. I want to minimize context switching.

**Comment by pkobrien** [comment]
plus, I like your idea of displaying the newly created tag (or applied tag) inline because the act of writing/tagging and the sequence sort of tells a story, as you've seen with my use of them

**Comment by pkobrien** [comment]
also will get us thinking about how to deal with branching and topic drift

**Comment by braid-sync** [comment]
may be solved by https://app.asana.com/0/46955048022389/79565089686062

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
as of https://github.com/braidchat/braid/commit/47eb5e47de5f9e1c31ccc5a5cac9ac9cbda216fa users see recommended tags in sidebar + can see last 50 messages

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
