### ISSUE TITLE
channels page

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#220]
when click on CHANNELS heading in sidebar, show all channels, descriptions and their subscription status

highlight new, popular, trending, etc.

indicate # of subscribers / channel

this can replace your subscription management page

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/83676695925662/f
---[aa]

**Comment by braid-sync** [comment]
related https://app.asana.com/0/46955048022389/83418134441075

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by rafd** [comment]
created channels page:
https://github.com/braidchat/braid/commit/4cb6d046af45e2c0b079c1d5ac175b4ed8af84ba

**Comment by rafd** [comment]
made highlighting channels. it's own task: https://github.com/braidchat/meta/issues/228
