### ISSUE TITLE
click on users icon in header should show list of all users a(s a page)

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#225]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/83676695925677/f
---[aa]

**Comment by rafd** [comment]
page is already prepared, but is empty

**Comment by CommonCreative** [comment]
I have submitted a pull request. Still needs a bit of work with CSS and also a Total Count - perhaps something like Slack has "55/100" etc

https://github.com/braidchat/braid/pull/12
