### ISSUE TITLE
indicate new messages / where a user last left off

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#23]
when a thread re-opens in the inbox OR when a user comes back from having the window/app out of focus…

for each thread, indicate new messages
...with a line like in slack
...highlight recent messages

replying to the thread should reset the display

closing the thread would indicate that all messages were read

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/78968160591834/f
---[aa]

**Comment by pkobrien** [comment]
context switching is what this is all about. when I switch back to the braid tab I should be able to glance at the screen and immediately know what deserves my attention and the context and relevancy. Bam!

**Comment by braid-sync** [comment]
looks like we’ll need to keep track of when each user last interacted with a thread… 

if closing a thread and sending a message are the only interactions, then we could calculate the time by using: latest-message-timestamp-of-user-in-this-thread and datomic-timestamp-of-user-open-status-of-thread. 

…OR, we could store the information explicitly in the database, ex. a last-message-seen-by-user for each thread,

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
done: https://github.com/braidchat/braid/commit/ce42eed87c4256822a42fc21be0b04cee46e98ca

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
