### ISSUE TITLE
refactor channel-page special-case

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#276]
https://github.com/braidchat/braid/commit/d7a6345f2a54881c957067d659ab525696ff9a7b

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/85671954216259/f
---[aa]

**Comment by jamesnvc** [comment]
closed by https://github.com/braidchat/braid/commit/a7de37c858222c47aedbc16527579a36a0ec2466
