### ISSUE TITLE
title attr of timestamps should be the entire date-time

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#282]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/85671954216337/f
---[aa]

**Comment by jdhorwitz** [comment]
This might be one I'm capable of trying, not quite sure.

**Comment by braid-sync** [comment]
resolved https://github.com/braidchat/braid/pull/9

[--- Commented from Asana.com
#commenter Brandon
---[aa]
