### ISSUE TITLE
do not require an avatar

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#29]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/78968160591581/f
---[aa]

**Comment by pkobrien** [comment]
On the other hand, make it super, super easy to create/change one's avatar, whether that be a photo, icon, graphic, system-generated thing, or whatever results in an array of pixels.

**Comment by braid-sync** [comment]
see https://app.asana.com/0/46955048022389/80471815316008

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by pkobrien** [comment]
I don't have an asana account. Should I.

**Comment by rafd** [comment]
@pkobrien unito.io is working on making the links to other issues show up as github links, not asana

**Comment by pkobrien** [comment]
cool

**Comment by braid-sync** [comment]
avatar, password, username not required for public registration

[--- Commented from Asana.com
#commenter James Cash
---[aa]
