### ISSUE TITLE
don’t show existing emails in invite UI

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#314]
just decide whether to send email & invite existing user server-side

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/78946865602817/f
---[aa]

**Comment by jamesnvc** [comment]
braid sync bug? I thought this was closed?

**Comment by braid-sync** [comment]
please review. if emails are no longer accessible to client-side, just close this

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
