### ISSUE TITLE
show images, links in an embed area below the message

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#321]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/88115967674058/f
---[aa]

**Comment by rafd** [comment]
<img width="707" alt="screenshot 2016-03-22 17 45 04" src="https://cloud.githubusercontent.com/assets/89664/13970293/d92ba23a-f055-11e5-86ec-bf80a8ee4d7b.png">

**Comment by rafd** [comment]
also worth considering alternative layout for certain embeds:

<img width="360" alt="screenshot 2016-03-22 17 52 27" src="https://cloud.githubusercontent.com/assets/89664/13970469/e5f1a11c-f056-11e5-828f-23f0a6611e8f.png">

**Comment by rafd** [comment]
addressed by: https://github.com/braidchat/braid/commit/ceed2248bc3bd79ca1733df2be0b4955918a9ff4
