### ISSUE TITLE
Om.now vs. Om.next vs. Reagent vs. Re-frame vs. ???

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#377]
Braid is currently written with om.now, which works, but there are some warts and long term concerns. We never really evaluated our choices (b/c when Braid started it was a weekend project and om.now was what the devs knew)

Since then... I've done a lot more work with om.now, om.next, reagent and re-frame, and I think, if we are ever going to transition, sooner is better than later.

The rest of this post is to serve as a wiki of the pros / cons of each choice:

---------

om.now
- single cursor pattern breaks down, have to use both cursors and subscribers 
- danger of closing over variables
- will be end of life when om.next stable?
- even David admits these warts (its what motivated om.next)

om.next
- reconciler is magic / incomprehensible to me
- reconciler requires work ex. by_id
- when building penyo-cms, I felt like I was fighting the declarative query stuff the whole time
- could follow idea of 'views define nested queries that get passed' without all the reconciler magic
- using it w/ datascript was awesome, but could be done w om.now or reagent

reagent
- allows for less verbose simple components
- composing functions with reactions is awesome, I feel in control (as opposed to om.next reconciler magic)
- some folks worried about magic of ratoms?? perf issues??
- no refs support??

reframe
- lib itself has very little code, its really just the single-global-atom pattern applied to reagent
- architecture is very good idea (only touch state via global reader and writer handlers), but can do it without reframe
- can still use reframe and reagent + local state (did that for "panels" so that global state would not  be polluted with cursor position state)
- may be nice to be able to directly access app-state occasionally???

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/106918617922705/f
---[aa]

**Comment by jaredly** [comment]
I tried using om/next on a thing, and its still reeeally early days... I'd recommend against it for the same reason I recommend against relay for js :D it's not ready, there isn't enough documentation, there's still some missing functionality, and API things are subject to change. Investing now is too early imo.
I really like reagent / re-frame. Very simple conceptually (vs om/next is pretty complex conceptually).

The cons I see for re-frame are:
- everything's global state, e.g. you're registering your subscriptions, handlers, etc globally.
- for many cases you might as well just use reagent by itself :)

in my tests reagent also ended up being **tons** faster than om/next for my use case (~1000 nodes in nested trees)

**Comment by CommonCreative** [comment]
I noticed that there is a mix of both Reagent and Om throughout the project. Seems to be mainly split between Mobile and Desktop. I'm guessing this is to trial the two different libs. 

In my eyes Reagent looks a lot simpler to use (haven't used it). The main battle here seems to be Client/Server communication.

**Comment by braid-sync** [comment]
we’ve decided to transition towards reagent

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
