### ISSUE TITLE
set up a braid group inside of hosted braid

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#4]

**Comment by pkobrien** [comment]
In the most minimal amount of time that you can spare for this, could you possibly add just a detail or two addressing:

* the primary problem this solves (or the biggest benefit it brings)

* the magnitude of work needed to get this done

* any resources you need to get this done

**Comment by rafd** [comment]
perhaps best to just rename clojurians to braid

**Comment by rafd** [comment]
We already have a hosted instance.

I'm just wondering if it's better to discuss braid under a clojurians group under braid (which is what everyone is invited to) or a braid group.

**Comment by pkobrien** [comment]
discussion can't be pre-compartmentalized - haven't we learned that with all my nonsense

**Comment by pkobrien** [comment]
no balkanization - need flexible, dynamic, real-time morphing of ui and convos

**Comment by pkobrien** [comment]
need to experiment and experience more - this will fall out of our use of the system if we let it

**Comment by rafd** [comment]
renamed the clojurians group to braid
