### ISSUE TITLE
add ability to invite people to a private group via a link (instead of an email)

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#437]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/133960831588945/f
---[aa]

**Comment by braid-sync** [comment]
would this be a one-use-only link, or anyone with the link can join?

[--- Commented from Asana.com
#commenter James Cash
---[aa]

**Comment by braid-sync** [comment]
I'd be okay with "anyone with link can join" , but the link should be anonynomized, ie. with a nonce ; 

Discord does "time limited" invite links, but, that's not necessary atm

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
Sounds good

[--- Commented from Asana.com
#commenter James Cash
---[aa]

**Comment by rafd** [comment]
Addressed by: https://github.com/braidchat/braid/commit/b3fe0950b1c0e5ca48b90674514353e0824b8f29
