### ISSUE TITLE
move list of "groups i have invitations to" to group add screen

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#446]
ie, what the [+] sign leads to

currently, they are under the user screen (accessed via the avatar) but that screen is meant to be group-specific (not global settings)  so, having invitations to other groups show under a group-specific page is not great

the 'add a group / join a group' page seems more appropriate

related: https://app.asana.com/0/40936868561782/103501632291721

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/135092275275094/f
---[aa]

**Comment by rafd** [comment]
Addressed by: https://github.com/braidchat/braid/pull/33
