### ISSUE TITLE
font size of compose field is much larger than threads

### ISSUE THREAD

**Issue by braid-sync** [braidchat/meta#493]
[--- This issue is linked with an Asana task
#attachments [screenshot-2016-06-03_23:31:14_EDT-04:00_1465011074.png](https://app.asana.com/app/asana/-/download_asset?asset_id=140616186630177)
#url https://app.asana.com/0/0/140616186630174/f
---[aa]

**Comment by rafd** [comment]
Fixed by: https://github.com/braidchat/braid/commit/3909b1cd12ddad5ca45f31206b3b0a029565a315
