### ISSUE TITLE
migrate to om.next

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#5]

**Comment by pkobrien** [comment]
I'm familiar with om and om.next and did some tutorial-level work with them, but nothing beyond that and have no idea how difficult it is to migrate from one to the other, let alone how you are going to do that with Braid. Could you provide just a tiny bit of a ballpark estimate of the magnitude of this effort and any big issues that you know off the top of your head?

**Comment by jamesnvc** [comment]
The way we've structured Braid, it probably would not be horribly difficult to port.  I would think it would likely be doable in a few days.  No huge issues are apparently to me at this point, but I've only done one little toy app in om.next.  Raf will probably have a better estimate, as he's written more real stuff with om.next.

**Comment by rafd** [comment]
We should be able to do it peace-by-peace (AFAIK om.next components can be used with om)

I’d rather do it sooner than later, b/c the code-base is only likely to grow from here, and om.now is as good as [deprecated] in my mind.

May start on this this week.

On January 11, 2016 at 11:02:17 AM, James Cash (notifications@github.com) wrote:

The way we've structured Braid, it probably would not be horribly difficult to port. I would think it would likely be doable in a few days. No huge issues are apparently to me at this point, but I've only done one little toy app in om.next. Raf will probably have a better estimate, as he's written more real stuff with om.next.

**Comment by pkobrien** [comment]
let me know if you need anything from me - I trust you guys to do the best thing here
