### ISSUE TITLE
indicate when in the conversation tags were added and by whom

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#50]
(e.g. “rafd added the tags #idonethis, #chat to the conversation”)
possibly a message by some sort of special user, which could be displayed in a distinct way (

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/43541873757936/f
---[aa]

**Comment by pkobrien** [comment]
good thinking

**Comment by braid-sync** [comment]
new way of doing tagging (where you have to mention it in a conversation) meets this requirement.

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]
