### ISSUE TITLE
good way to write bots

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#52]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/43581930897454/f
---[aa]

**Comment by pkobrien** [comment]
not sure what you mean

**Comment by rafd** [comment]
Related to plugins / integrations.

Like IRC bots.

For example, you could have the /giphy bot implemented separately (and I
could also block that POS)

Not a priority.

**Comment by pkobrien** [comment]
agreed not a priority and implies unbreakable api expectations
