### ISSUE TITLE
User pill hover visual glitch

### ISSUE THREAD

**Issue by jamesnvc** [braidchat/meta#595]
![screenshot-2016-08-21_20 45 30_edt-04 00_1471826730](https://cloud.githubusercontent.com/assets/38405/17840933/7f0821cc-67e0-11e6-9473-a07f01ab9f5f.png)

**Comment by rafd** [comment]
Fixed by: https://github.com/braidchat/braid/commit/4b2a456f74e07d031faee6123c4450b19246230f
