### ISSUE TITLE
User icon overflows in user pill hover popup

### ISSUE THREAD

**Issue by jamesnvc** [braidchat/meta#596]
![screenshot-2016-08-22_10 20 17_edt-04 00_1471875617](https://cloud.githubusercontent.com/assets/38405/17858344/4f2d37d0-6853-11e6-869a-bb73a5f0ee03.png)

**Comment by rafd** [comment]
So the issue here is that the icon is covering the "ONLINE" text?

**Comment by braid-sync** [comment]
jamesnvc commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
Yes, and it seems to be impinging on the "profile text here" section

**Comment by braid-sync** [comment]
raf commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
that part is "as designed" it's meant to break out of the header background;
it's also why the first row has the time on it (not fully implemented); it's similar to how your profile image juts out in facebook

**Comment by braid-sync** [comment]
jamesnvc commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
ah, okay

**Comment by braid-sync** [comment]
jamesnvc commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
Image is still getting cut off on the right edge sometimes too

**Comment by jamesnvc** [comment]
![screenshot-2016-08-22_10 51 24_edt-04 00_1471877484](https://cloud.githubusercontent.com/assets/38405/17859142/77114f18-6856-11e6-9799-d2bed50d129d.png)

**Comment by braid-sync** [comment]
raf commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
hmmmmmmm that shouldn't happen

**Comment by braid-sync** [comment]
raf commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
@55b65d64-0c21-43c4-894f-5fd3c2b5f827

**Comment by braid-sync** [comment]
raf commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
i'm not seeing it:

**Comment by braid-sync** [comment]
raf commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
https://s3.amazonaws.com/chat.leanpixel.com/uploads/57bb140f-0588-433c-af3c-ad3e20daa64d/Screenshot%202016-08-22%2011.02.13.png

**Comment by braid-sync** [comment]
jamesnvc commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
maybe a firefox thing?

**Comment by braid-sync** [comment]
jamesnvc commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
yeah, looks as expected on chromium for me, guess it's a gecko difference

**Comment by braid-sync** [comment]
raf commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
k, i'll take a look

**Comment by braid-sync** [comment]
raf commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
looks fine in my firefox too... refresh client maybe?

**Comment by braid-sync** [comment]
jamesnvc commented via [braid](https://braid.chat/572e4ed2-a786-45bd-9859-430b7a68cc70/thread/bda0d697-db97-49af-9a1b-b85582e706dd):
oh huh, there it goes; how odd
