### ISSUE TITLE
Pills appear below thread content

### ISSUE THREAD

**Issue by jamesnvc** [braidchat/meta#597]
When hovering an inline pill, pills in the thread header appear okay
![screenshot-2016-08-22_10 20 29_edt-04 00_1471875629](https://cloud.githubusercontent.com/assets/38405/17858365/6d29b024-6853-11e6-9e26-c15668ea51fc.png)
![screenshot-2016-08-22_10 30 28_edt-04 00_1471876228](https://cloud.githubusercontent.com/assets/38405/17858380/7948df38-6853-11e6-8748-28e35f6e0f35.png)

**Comment by rafd** [comment]
Fixed by: https://github.com/braidchat/braid/commit/402a3b9549111d02301e21199123af90355cafb5
