### ISSUE TITLE
show option to not tag in tag autocomplete

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#60]
ex. so you can write  “We are #1” (without it being a tag)

**Comment by rafd** [comment]
should be simple enough with the autocomplete implementation; currently, we always nuke the tag after leaving the autocomplete UI, but we could:
a) if hit exit the UI (by ESC or click outside), just leave the #text
b) provide an option within the autocomplete UI to do the same

**Comment by rafd** [comment]
(A) from above comment is done

**Comment by jamesnvc** [comment]
You can already do that, just type off the end of the autocomplete without selecting anything

**Comment by jamesnvc** [comment]
Do we need an option within autocomplete? As it is, user can just ignore the dropdown and it'll be plain text

**Comment by rafd** [comment]
I think it would be more discoverable and trivial to implement. (I would
still keep the functionality of 'ignore and it will be plain text')

**Comment by pkobrien** [comment]
What about "we are ##1"

**Comment by pkobrien** [comment]
is there a list of autocomplete initiators, like is # for tags and : for emoji

**Comment by pkobrien** [comment]
are there conventions in other systems, such as slack and github, that would be useful to mimic due to familiarity of conventions by users and keystroke habits

**Comment by jamesnvc** [comment]
Right now only "#" starts autocomplete

**Comment by rafd** [comment]
fixed by https://github.com/braidchat/braid/commit/26fddb57236b88141aa3d60c643c6e6b8f57e388
