### ISSUE TITLE
better way to render long threads

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#61]

**Comment by pkobrien** [comment]
the new way is better, but isn't scrolling when I add replies

**Comment by rafd** [comment]
scrolling now :) https://github.com/braidchat/braid/commit/b812e01665054b66edc12493534ec3600ecdb4b0

**Comment by pkobrien** [comment]
when an old convo pops up because of someone else's reply I think it is set to the top and not necessarily scrolled to the beginning of the new content.

**Comment by rafd** [comment]
good catch; fixed: https://github.com/braidchat/braid/commit/bc212ee7ae59629b742c4ddae698a6872542e805
