### ISSUE TITLE
direct messages

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#67]

**Comment by rafd** [comment]
possibly create a thread with the tag being a ref to the user instead of a tag

**Comment by pkobrien** [comment]
something

**Comment by jamesnvc** [comment]
You can use mentions for this now, since if the thread has no tags, only those mentioned can see it

**Comment by rafd** [comment]
yep, i'm happy to close this; may need better ux, etc. but that can be a different task

**Comment by pkobrien** [comment]
this was a stupid ticket - not clear initially, never got clarified, I don't know what we accomplished, and now its closed - fortunately I don't care, but lets get better at this

**Comment by jamesnvc** [comment]
@pkobrien I think this was one of the tasks that got pulled in when we mirrored all our Asana tasks to github; we will try to be more clear moving forwards!
