### ISSUE TITLE
rethink order of threads in UI

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#71]

**Comment by pkobrien** [comment]
need further description

**Comment by rafd** [comment]
may be a stale issue.

there was a time when we didn't sort the conversations by anything, so when a conversation 'came back' it would be in a (effectively) random spot

@jamesnvc have we changed this?

**Comment by rafd** [comment]
it is currently created-at of the first message in the conversation, which is not ideal, however, having it with created-at of last message resulted in the threads jumping around a lot , which was also not ideal

**Comment by pkobrien** [comment]
mostly I don't like when the one that has keyboard focus gets move - can we make it lock into position somehow

**Comment by rafd** [comment]
changed order in https://github.com/braidchat/braid/commit/8f66b4a084b2209e7649f8eccccf572cd171c95f

by default, threads are now shown from most-recent -> older based on your-last-message-in-that-thread
(this limits jumping around compared to anyones-last-message-in-a-thread)

for search, it's just done by anyones-last-message-in-a-thread, also most-recent -> older

closing for now, but may reopen in a few days if the solution isn't good enough
