### ISSUE TITLE
code snippet support

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#75]
[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/78693400450349/f
---[aa]

**Comment by pkobrien** [comment]
I use the single-quote and triple single-quote conventions from slack quite a bit

**Comment by jamesnvc** [comment]
Hm, so I really want to make it easy to do fancy things with formatting messages, but the way I would tend to do such a things is write an Instaparse grammar to parse, then transform.  However, when I tried using instaparse in clojurescript previously, for just extracting links, it was way too slow.  Anyone aware of a faster equivalent?  The current way this is done is fairly gross (https://github.com/braidchat/braid/blob/master/src/chat/client/views/helpers.cljs#L15)

**Comment by rafd** [comment]
embed an existing js highlighter for now?

**Comment by jamesnvc** [comment]
Will that break things though? I don't think React likes having the dom modified out from under it

**Comment by rafd** [comment]
there seem to be react highlighter libraries

also, it's been ok in the past when we've embedded things and marked them as 'react no touchy' [sic]

**Comment by pkobrien** [comment]
contact the instaparse guys and tell them your concern about performance and see if they have suggestions
