### ISSUE TITLE
figure out a tool to manage tasks/issues

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#8]
asana

http://unito.io/

https://www.zenhub.io/
https://overv.io/
https://www.assembla.com/workspaces/repositories-features
https://zube.io/
https://www.breeze.pm/
https://waffle.io/

**Comment by pkobrien** [comment]
I've used a variety of tools for this in the past and none was satisfactory. Would love to get some solid recommendations from others who have been satisfied with a tool. Perhaps someone could even set up an example that we can try out to see if it will work for how folks would like to manage tasks for this project. Any help from the community would be greatly appreciated. This is the kind of task that anyone could help with. I will give a gold star to the hero who makes this happen. It is extremely important to me that we do this well and not get bogged down by red tape and miscommunication. :-)

**Comment by rafd** [comment]
James  and I use Asana currently for all of our projects, hence my use of http://unito.io to sync between asana and github.

My plan is to invite core contributors to Asana if they prefer it over using github issues. 

Hopefully this will be good enough. If there are problems, we can revisit.

We do need to improve tagging and better indication of what the priorities are.

**Comment by pkobrien** [comment]
we need something good here, soon, including lots of hand-holding for people like me who are stretched to their limits and don't have the energy to learn anything new on their own. and I will bitch and moan the whole time but you know that and deal with it so well now that I don't expect that to be a problem
