### ISSUE TITLE
closing threads while scrolled to the side truncates window

### ISSUE THREAD

**Issue by jamesnvc** [braidchat/meta#98]
i.e., having more than a screenful of threads, scroll to the right, close a thread — I can't scroll back, end up with half a thread on the screen

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/79485621940774/f
---[aa]

**Comment by jamesnvc** [comment]
Like:
![screen shot 2016-01-15 at 09 29 01](https://cloud.githubusercontent.com/assets/38405/12355425/8769ae30-bb6a-11e5-9ed6-0f0321e66ed0.PNG)

No scrollbars, need to refresh to move over

**Comment by jamesnvc** [comment]
Can't consistently repro this though :/

**Comment by braid-sync** [comment]
have you experienced this recently?

[--- Commented from Asana.com
#commenter Rafal Dittwald
---[aa]

**Comment by braid-sync** [comment]
Nope, we can probably close this & re-open later if people report it

[--- Commented from Asana.com
#commenter James Cash
---[aa]
